name: Node CI

on: [push]

jobs:
    build:
        name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [12.x, 13.x, 14.x]
                os: [ubuntu-latest, macOS-latest]

        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install
              run: yarn --frozen-lockfile

            - name: lerna info
              run: yarn lerna info

            - name: build
              run: yarn lerna run build

            - name: test
              run: yarn lerna run test --parallel -- -- --coverage --watchAll=false
