name: Main workflow

on:
    push:
        branches:
            - master
            - beta
    pull_request:
        branches:
            - master

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x]
                os: [ubuntu-latest]

        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install
              run: yarn --frozen-lockfile

            - name: install electron build deps
              run: sudo apt-get install -y libgconf-2-4

            - name: lerna info
              run: yarn lerna info

            - name: build
              run: yarn lerna run build

            - name: make CLI script executable
              run: chmod +x cli/dist/index.js # make the script executable for tests

            - name: test
              run: yarn lerna run test --parallel -- -- --coverage --watchAll=false

            - name: Stryker mutation testing
              run: yarn lerna run stryker:run

            - name: create version and publish
              if: github.ref == 'refs/heads/master'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                  yarn lerna publish patch --yes --message "publish %s - ci skip" --no-push --create-release github --conventional-commits
                  yarn lerna run build --scope @keyrier/ui
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Push new version changes
              if: github.ref == 'refs/heads/master'
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: deploy on gh-pages
              if: github.ref == 'refs/heads/master'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./ui/build
