name: Node CI

on: [push]

jobs:
    build-core:
        name: core build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [12.x, 13.x, 14.x]
                os: [ubuntu-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install, build, and test
              run: |
                  yarn --frozen-lockfile
                  yarn workspace @keyrier/core test --coverage --watchAll=false
                  yarn workspace @keyrier/core build
              env:
                  CI: true

    build-ui:
        name: ui build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x]
                os: [ubuntu-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install, build, and test
              run: |
                  yarn --frozen-lockfile
                  yarn workspace @keyrier/ui test --coverage --watchAll=false
                  yarn workspace @keyrier/ui build
              env:
                  CI: true

    build-cli:
        name: cli build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x]
                os: [ubuntu-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install, build, and test
              run: |
                  yarn --frozen-lockfile
                  yarn workspace @keyrier/cli test --coverage --watchAll=false
                  yarn workspace @keyrier/cli build
              env:
                  CI: true
