name: Node CI

on: [push]

jobs:
    build:
        name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [12.x, 13.x, 14.x]
                os: [ubuntu-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install, build, and test
              run: |
                  yarn --frozen-lockfile
                  yarn lerna info
                  yarn lerna bootstrap
                  yarn lerna run build
                  yarn lerna run test -- -- --coverage --watchAll=false
              env:
                  CI: true
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
