name: Main workflow

on:
    push:
        branches:
            - master
            - beta
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x]
                os: [ubuntu-latest]

        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install
              run: yarn --frozen-lockfile

            - name: install electron build deps
              run: sudo apt-get install -y libgconf-2-4

            - name: lerna info
              run: yarn lerna info

            - name: build
              run: yarn lerna run build

            - name: test
              run: yarn lerna run test --parallel -- -- --coverage --watchAll=false

            - name: deploy on gh-pages
              if: github.ref == 'master'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./ui/build
